networks:
    my-network:

services:
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
            target: dev
        ports:
            - "3000:80"
        volumes:
            - ./app:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - my-network

    php-fpm:
        build:
            context: .
            dockerfile: app/Dockerfile
            target: dev
        volumes:
            - ./app/public:/var/www/html/public
            - ./app/src:/var/www/html/src
        networks:
            - my-network

    postgres:
        build:
            context: .
            dockerfile: postgres/Dockerfile
            target: dev
        environment:
            POSTGRES_PASSWORD: weakpassword
            POSTGRES_DB: biblioteca
        networks:
            - my-network
